defaults: &defaults
  docker:
    - image: cimg/node:lts

version: 2.1
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - lib
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test
